tls:
  certificates:
    - certFile: "/etc/traefik/ssl/wildcard.pem"
      keyFile: "/etc/traefik/ssl/wildcard-key.pem"
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/ssl/wildcard.pem"
        keyFile: "/etc/traefik/ssl/wildcard-key.pem"
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
        - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
      sniStrict: false
      preferServerCipherSuites: true